version: '3.4'
services:
  grpc-server:
    image: node:12
    ports:
      - "50051:50051"
    volumes:
      - .:/data
    command:
      - node
      - /data/server.js
    
  grpc-gateway:
    build:
      context: .
      target: gateway
    command:
      - ./gateway
      - -grpc-server-endpoint=grpc-server:50051
    links:
      - grpc-server
    ports:
      - "8081:8081"
    
  swagger-json:
    build:
      context: .
      target: static
    links:
      - grpc-gateway
    ports:
      - "8080:80"
    
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8888:8080"
